baseURL: /
languageCode: zh-cn
title: blog
theme: hugo-paper # ä¸»é¢˜åå­—ï¼Œå’Œthemesæ–‡ä»¶å¤¹ä¸‹çš„ä¸€è‡´
languages:
  en:
    languageName: "English"
    weight: 1
    profileMode:
      enabled: true
      title: (ã€ƒ'nwjf'ã€ƒ)
      subtitle:
      # subtitle: "ğŸ§¨å­¦è€Œæ—¶ä¹ ä¹‹ï¼Œä¸äº¦è¯´ä¹ï¼Ÿæœ‰æœ‹è‡ªè¿œæ–¹æ¥ï¼Œä¸äº¦ä¹ä¹ï¼Ÿ<br/>ğŸ‘‡è”ç³»æ–¹å¼"
      # imageUrl: "img/head.png"
      imageTitle:
      imageWidth: 150
      imageHeight: 150
      buttons:
        - name: æ–‡ç« 
          url: posts
        - name: æ ‡ç­¾
          url: tags
        - name: å…³äº
          url: about
        - name: å‹æƒ…é“¾æ¥
          url: links
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 1
        - identifier: posts
          name: æ–‡ç« 
          url: /posts
          weight: 3
        - identifier: tags
          name: æ ‡ç­¾
          url: /tags
          weight: 15
        - identifier: archives
          name: æ—¶é—´è½´
          url: /archives
          weight: 20
        - identifier: about
          name: å…³äº
          url: /about
          weight: 50
        - identifier: links
          name: å‹é“¾
          url: /links
          weight: 60

outputs:
  home:
    - HTML
    - RSS
    - JSON